version: '3'
services:
  ionic:
    image: ionic4-dev
    ports:
      - 8100:8100 # ionic dev server
    #- "0.0.0.0:35729:35729" # livereload
    #- "0.0.0.0:53703:53703" # websocket
    volumes:
      - type: bind
        source: ~/Github/QLOCKGENERATOR
        target: /app
    container_name: ionic-dev
    restart: unless-stopped

